version: '3.8'

services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/models
      - ../datasets:/datasets
  app:
    build: ./app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - api
